---
title: "bike"
author: "575 Lab"
date: "2020/10/29"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(hrbrthemes))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(plotly))
bike <- read_csv("bike_day.csv")
bike <- bike[complete.cases(bike), ]
```


```{r heatmap}
# temp heatmap
bike %>% transmute(temp = cut_number(temp, 8), cnt = cut_number(cnt, 8)) %>% count(temp, cnt) %>% ggplot(aes(temp, cnt)) + geom_tile(aes(fill = n)) + scale_x_discrete(labels = abbreviate) + scale_fill_viridis_c()

# hum heatmap
bike %>% transmute(hum = cut_number(hum, 8), cnt = cut_number(cnt, 8)) %>% count(hum, cnt) %>% ggplot(aes(hum, cnt)) + geom_tile(aes(fill = n)) + scale_x_discrete(labels = abbreviate) + scale_fill_viridis_c()

# windspeed heatmap
bike %>% transmute(windspeed = cut_number(windspeed, 8), cnt = cut_number(cnt, 8)) %>% count(windspeed, cnt) %>% ggplot(aes(windspeed, cnt)) + geom_tile(aes(fill = n)) + scale_x_discrete(labels = abbreviate) + scale_fill_viridis_c()

# atemp heatmap
bike %>% transmute(atemp = cut_number(atemp, 8), cnt = cut_number(cnt, 8)) %>% count(atemp, cnt) %>% ggplot(aes(atemp, cnt)) + geom_tile(aes(fill = n)) + scale_x_discrete(labels = abbreviate) + scale_fill_viridis_c()

# season plot
bike %>% ggplot(aes(as.factor(season), cnt)) + geom_violin() + scale_x_discrete(labels = abbreviate)

# holiday plot
bike %>% ggplot(aes(as.factor(holiday), cnt)) + geom_violin() + scale_x_discrete(labels = abbreviate)
```


```{r outlier}
# computer mean and sd
temp_mean = mean(bike$temp)
temp_sd = sd(bike$temp)
hum_mean = mean(bike$hum)
hum_sd = sd(bike$hum)
atemp_mean = mean(bike$atemp)
atemp_sd = sd(bike$atemp)
windspeed_mean = mean(bike$windspeed)
windspeed_sd = sd(bike$windspeed)

# compute table without outliers beyond 3 standard deviation
bike.clean <- bike %>% filter(temp <= temp_mean+3*temp_sd, hum <= hum_mean+3*hum_sd, atemp <= atemp_mean+3*atemp_sd, windspeed <= windspeed_mean+3*windspeed_sd)

# calculate percentage of datapoints considered
removedt <- (1 - nrow(bike.clean)/nrow(bike))*100
percentage_tibble <- tribble(~Variable, ~Percentage_Removed, "Overall", removedt)
(percentage_tibble)
```


```{r cov}
# scatter matrix
bike.clean %>% select(cnt, temp, hum, windspeed, atemp, season, holiday) %>% ggpairs(lower = list(continuous = wrap("points", alpha = 0.3, size=0.1)))
```


```{r OLS}
# calculate OLS
m.ols <- lm(cnt ~ temp, data = bike.clean)
summary(m.ols)
round(confint(m.ols,level=0.95),6)
vcov(m.ols)
ggplot(bike.clean %>% add_predictions(m.ols), aes(temp, cnt)) + geom_point(size = 0.1) + geom_line(aes(y=pred), color = "blue")
```


```{r QLS}
# calculate QLS
m.qls <- bike.clean %>% lm(cnt ~ temp + I(temp^2), .)
summary(m.qls)
round(confint(m.qls,level=0.95),6)
vcov(m.qls)
ggplot(bike.clean %>% add_predictions(m.qls), aes(temp, cnt)) + geom_point(size = 0.1) + geom_line(aes(y=pred), color = "blue")
```


```{r MLS}
m.mls <- lm(cnt ~ temp + windspeed + + hum + as.factor(season) + as.factor(holiday) - 1, data = bike.clean)
summary(m.mls)
coef(m.mls)
```


```{r plotly, eval = FALSE}
# this portion constructs the two 3D plots.
bike.clean <- bike.clean %>% add_predictions(m.mls)
bike.clean %>% plot_ly(x = ~temp, y = ~windspeed, z = ~cnt, color = ~as.factor(season), colors = c('Orange', 'Purple')) %>% add_markers(size = 4)
bike.clean %>% plot_ly(x = ~temp, y = ~windspeed, z = ~pred, color = ~as.factor(season), colors = c('#BF382A', '#0C4B8E')) %>% add_markers(size = 4)
```


```{r interactions}
m.mls <- lm(cnt ~ temp + windspeed + + hum + as.factor(season) + as.factor(holiday) + temp:hum + temp:windspeed + hum:windspeed - 1, data = bike.clean)
summary(m.mls)
coef(m.mls)
```


```{r residual}
# first build residual from quadratic model to compare against mls
StanResQLS <- rstandard(m.qls)

# standardize for mls and plotting
StanResMLS <- rstandard(m.mls)
bike.clean %>% ggplot() + geom_point(aes(cnt, StanResQLS, color = "Quadratic"), size = 0.1) +
geom_point(aes(cnt, StanResMLS, color = "MLS"), size = 0.1) +
geom_hline(yintercept=2,color='blue') + geom_hline(yintercept=-2, color='blue') +
scale_color_manual(name = element_blank(), labels = c("MLS","Quadratic"), values = c("red","blue")) +
labs(y = "Standarized Residual") + ggtitle("Standarized Residuals Plot")

# fitted residuals
qfit = fitted(m.qls)
mfit = fitted(m.mls)

bike.clean %>% ggplot() + geom_point(aes(qfit, StanResQLS, color = "Quadratic"), size = 0.1) + geom_point(aes(mfit, StanResMLS, color = "MLS"), size = 0.1) +
geom_hline(yintercept=2,color='blue') + geom_hline(yintercept=-2, color='blue') +
scale_color_manual(name = element_blank(), labels = c("MLS","Quadratic"), values = c("red","blue")) +
labs(y = "Standarized Residual") + labs(x = "Fitted value") +
ggtitle("Standarized Residuals Plot (Fitted) ")
```